<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->char('iso',2);
            $table->string('name',80);
            $table->string('nicename',80);
            $table->char('iso3',3);
            $table->char('numcode',3);
            $table->integer('phonecode');
            $table->string('nationality',80);
            $table->enum('status',['Enable', 'Disable'])->default('Enable');
        });

        \DB::insert("INSERT INTO `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`,`nationality`, `status`) VALUES
            (1, 'AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', '4', 93, 'Afghan', 'Enable'),
            (2, 'AL', 'ALBANIA', 'Albania', 'ALB', '8', 355, 'Albanian', 'Enable'),
            (3, 'DZ', 'ALGERIA', 'Algeria', 'DZA', '12', 213, 'Algerian', 'Enable'),
            (4, 'AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', '16', 1684, 'American Samoan', 'Enable'),
            (5, 'AD', 'ANDORRA', 'Andorra', 'AND', '20', 376, 'Andorran', 'Enable'),
            (6, 'AO', 'ANGOLA', 'Angola', 'AGO', '24', 244, 'Angolan', 'Enable'),
            (7, 'AI', 'ANGUILLA', 'Anguilla', 'AIA', '660', 1264, 'Anguillan', 'Enable'),
            (8, 'AQ', 'ANTARCTICA', 'Antarctica', '', '', 0, 'Antarctic', 'Enable'),
            (9, 'AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', '28', 1268, 'Antiguan or Barbudan', 'Enable'),
            (10, 'AR', 'ARGENTINA', 'Argentina', 'ARG', '32', 54, 'Argentine', 'Enable'),
            (11, 'AM', 'ARMENIA', 'Armenia', 'ARM', '51', 374, 'Armenian', 'Enable'),
            (12, 'AW', 'ARUBA', 'Aruba', 'ABW', '533', 297, 'Aruban', 'Enable'),
            (13, 'AU', 'AUSTRALIA', 'Australia', 'AUS', '36', 61, 'Australian', 'Enable'),
            (14, 'AT', 'AUSTRIA', 'Austria', 'AUT', '40', 43, 'Austrian', 'Enable'),
            (15, 'AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', '31', 994, 'Azerbaijani, Azeri', 'Enable'),
            (16, 'BS', 'BAHAMAS', 'Bahamas', 'BHS', '44', 1242, 'Bahamian', 'Enable'),
            (17, 'BH', 'BAHRAIN', 'Bahrain', 'BHR', '48', 973, 'Bahraini', 'Enable'),
            (18, 'BD', 'BANGLADESH', 'Bangladesh', 'BGD', '50', 880, 'Bangladeshi', 'Enable'),
            (19, 'BB', 'BARBADOS', 'Barbados', 'BRB', '52', 1246, 'Barbadian', 'Enable'),
            (20, 'BY', 'BELARUS', 'Belarus', 'BLR', '112', 375, 'Belarusian', 'Enable'),
            (21, 'BE', 'BELGIUM', 'Belgium', 'BEL', '56', 32, 'Belgian', 'Enable'),
            (22, 'BZ', 'BELIZE', 'Belize', 'BLZ', '84', 501, 'Belizean', 'Enable'),
            (23, 'BJ', 'BENIN', 'Benin', 'BEN', '204', 229, 'Beninese, Beninois', 'Enable'),
            (24, 'BM', 'BERMUDA', 'Bermuda', 'BMU', '60', 1441, 'Bermudian, Bermudan', 'Enable'),
            (25, 'BT', 'BHUTAN', 'Bhutan', 'BTN', '64', 975, 'Bhutanese', 'Enable'),
            (26, 'BO', 'BOLIVIA', 'Bolivia', 'BOL', '68', 591, 'Zimbabwean', 'Enable'),
            (27, 'BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', '70', 387, 'Bosnian or Herzegovinian', 'Enable'),
            (28, 'BW', 'BOTSWANA', 'Botswana', 'BWA', '72', 267, 'Motswana, Botswanan', 'Enable'),
            (29, 'BV', 'BOUVET ISLAND', 'Bouvet Island', '', '', 0, 'Bouvet Island', 'Enable'),
            (30, 'BR', 'BRAZIL', 'Brazil', 'BRA', '76', 55, 'Brazilian', 'Enable'),
            (31, 'IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', '', '', 246, 'BIOT', 'Enable'),
            (32, 'BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', '96', 673, 'Bruneian', 'Enable'),
            (33, 'BG', 'BULGARIA', 'Bulgaria', 'BGR', '100', 359, 'Bulgarian', 'Enable'),
            (34, 'BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', '854', 226, 'Burkinabé', 'Enable'),
            (35, 'BI', 'BURUNDI', 'Burundi', 'BDI', '108', 257, 'Burundian', 'Enable'),
            (36, 'KH', 'CAMBODIA', 'Cambodia', 'KHM', '116', 855, 'Cambodian', 'Enable'),
            (37, 'CM', 'CAMEROON', 'Cameroon', 'CMR', '120', 237, 'Cameroonian', 'Enable'),
            (38, 'CA', 'CANADA', 'Canada', 'CAN', '124', 1, 'Canadian', 'Enable'),
            (39, 'CV', 'CAPE VERDE', 'Cape Verde', 'CPV', '132', 238, 'Zimbabwean', 'Enable'),
            (40, 'KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', '136', 1345, 'Caymanian', 'Enable'),
            (41, 'CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', '140', 236, 'Central African', 'Enable'),
            (42, 'TD', 'CHAD', 'Chad', 'TCD', '148', 235, 'Chadian', 'Enable'),
            (43, 'CL', 'CHILE', 'Chile', 'CHL', '152', 56, 'Chilean', 'Enable'),
            (44, 'CN', 'CHINA', 'China', 'CHN', '156', 86, 'Chinese', 'Enable'),
            (45, 'CX', 'CHRISTMAS ISLAND', 'Christmas Island', '', '', 61, 'Christmas Island', 'Enable'),
            (46, 'CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', '', '', 672, 'Cocos Island', 'Enable'),
            (47, 'CO', 'COLOMBIA', 'Colombia', 'COL', '170', 57, 'Colombian', 'Enable'),
            (48, 'KM', 'COMOROS', 'Comoros', 'COM', '174', 269, 'Comoran, Comorian', 'Enable'),
            (49, 'CG', 'CONGO', 'Congo', 'COG', '178', 242, 'Zimbabwean', 'Enable'),
            (50, 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', '180', 242, 'Zimbabwean', 'Enable'),
            (51, 'CK', 'COOK ISLANDS', 'Cook Islands', 'COK', '184', 682, 'Cook Island', 'Enable'),
            (52, 'CR', 'COSTA RICA', 'Costa Rica', 'CRI', '188', 506, 'Costa Rican', 'Enable'),
            (53, 'CI', 'COTE D\'IVOIRE', 'Cote D\'Ivoire', 'CIV', '384', 225, 'Zimbabwean', 'Enable'),
            (54, 'HR', 'CROATIA', 'Croatia', 'HRV', '191', 385, 'Croatian', 'Enable'),
            (55, 'CU', 'CUBA', 'Cuba', 'CUB', '192', 53, 'Cuban', 'Enable'),
            (56, 'CY', 'CYPRUS', 'Cyprus', 'CYP', '196', 357, 'Cypriot', 'Enable'),
            (57, 'CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', '203', 420, 'Czech', 'Enable'),
            (58, 'DK', 'DENMARK', 'Denmark', 'DNK', '208', 45, 'Danish', 'Enable'),
            (59, 'DJ', 'DJIBOUTI', 'Djibouti', 'DJI', '262', 253, 'Djiboutian', 'Enable'),
            (60, 'DM', 'DOMINICA', 'Dominica', 'DMA', '212', 1767, 'Dominican', 'Enable'),
            (61, 'DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', '214', 1809, 'Dominican', 'Enable'),
            (62, 'EC', 'ECUADOR', 'Ecuador', 'ECU', '218', 593, 'Ecuadorian', 'Enable'),
            (63, 'EG', 'EGYPT', 'Egypt', 'EGY', '818', 20, 'Egyptian', 'Enable'),
            (64, 'SV', 'EL SALVADOR', 'El Salvador', 'SLV', '222', 503, 'Salvadoran', 'Enable'),
            (65, 'GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', '226', 240, 'Equatorial Guinean, Equatoguinean', 'Enable'),
            (66, 'ER', 'ERITREA', 'Eritrea', 'ERI', '232', 291, 'Eritrean', 'Enable'),
            (67, 'EE', 'ESTONIA', 'Estonia', 'EST', '233', 372, 'Estonian', 'Enable'),
            (68, 'ET', 'ETHIOPIA', 'Ethiopia', 'ETH', '231', 251, 'Ethiopian', 'Enable'),
            (69, 'FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', '238', 500, 'Falkland Island', 'Enable'),
            (70, 'FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', '234', 298, 'Faroese', 'Enable'),
            (71, 'FJ', 'FIJI', 'Fiji', 'FJI', '242', 679, 'Fijian', 'Enable'),
            (72, 'FI', 'FINLAND', 'Finland', 'FIN', '246', 358, 'Finnish', 'Enable'),
            (73, 'FR', 'FRANCE', 'France', 'FRA', '250', 33, 'French', 'Enable'),
            (74, 'GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', '254', 594, 'French Guianese', 'Enable'),
            (75, 'PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', '258', 689, 'French Polynesian', 'Enable'),
            (76, 'TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', '', '', 0, 'French Southern Territories', 'Enable'),
            (77, 'GA', 'GABON', 'Gabon', 'GAB', '266', 241, 'Gabonese', 'Enable'),
            (78, 'GM', 'GAMBIA', 'Gambia', 'GMB', '270', 220, 'Gambian', 'Enable'),
            (79, 'GE', 'GEORGIA', 'Georgia', 'GEO', '268', 995, 'Georgian', 'Enable'),
            (80, 'DE', 'GERMANY', 'Germany', 'DEU', '276', 49, 'German', 'Enable'),
            (81, 'GH', 'GHANA', 'Ghana', 'GHA', '288', 233, 'Ghanaian', 'Enable'),
            (82, 'GI', 'GIBRALTAR', 'Gibraltar', 'GIB', '292', 350, 'Gibraltar', 'Enable'),
            (83, 'GR', 'GREECE', 'Greece', 'GRC', '300', 30, 'Greek, Hellenic', 'Enable'),
            (84, 'GL', 'GREENLAND', 'Greenland', 'GRL', '304', 299, 'Greenlandic', 'Enable'),
            (85, 'GD', 'GRENADA', 'Grenada', 'GRD', '308', 1473, 'Grenadian', 'Enable'),
            (86, 'GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', '312', 590, 'Guadeloupe', 'Enable'),
            (87, 'GU', 'GUAM', 'Guam', 'GUM', '316', 1671, 'Guamanian, Guambat', 'Enable'),
            (88, 'GT', 'GUATEMALA', 'Guatemala', 'GTM', '320', 502, 'Guatemalan', 'Enable'),
            (89, 'GN', 'GUINEA', 'Guinea', 'GIN', '324', 224, 'Guinean', 'Enable'),
            (90, 'GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', '624', 245, 'Bissau-Guinean', 'Enable'),
            (91, 'GY', 'GUYANA', 'Guyana', 'GUY', '328', 592, 'Guyanese', 'Enable'),
            (92, 'HT', 'HAITI', 'Haiti', 'HTI', '332', 509, 'Haitian', 'Enable'),
            (93, 'HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', '', '', 0, 'Heard Island or McDonald Islands', 'Enable'),
            (94, 'VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', '336', 39, 'Zimbabwean', 'Enable'),
            (95, 'HN', 'HONDURAS', 'Honduras', 'HND', '340', 504, 'Honduran', 'Enable'),
            (96, 'HK', 'HONG KONG', 'Hong Kong', 'HKG', '344', 852, 'Hong Kong, Hong Kongese', 'Enable'),
            (97, 'HU', 'HUNGARY', 'Hungary', 'HUN', '348', 36, 'Hungarian, Magyar', 'Enable'),
            (98, 'IS', 'ICELAND', 'Iceland', 'ISL', '352', 354, 'Icelandic', 'Enable'),
            (99, 'IN', 'INDIA', 'India', 'IND', '356', 91, 'Indian', 'Enable'),
            (100, 'ID', 'INDONESIA', 'Indonesia', 'IDN', '360', 62, 'Indonesian', 'Enable'),
            (101, 'IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', '364', 98, 'Zimbabwean', 'Enable'),
            (102, 'IQ', 'IRAQ', 'Iraq', 'IRQ', '368', 964, 'Iraqi', 'Enable'),
            (103, 'IE', 'IRELAND', 'Ireland', 'IRL', '372', 353, 'Irish', 'Enable'),
            (104, 'IL', 'ISRAEL', 'Israel', 'ISR', '376', 972, 'Israeli', 'Enable'),
            (105, 'IT', 'ITALY', 'Italy', 'ITA', '380', 39, 'Italian', 'Enable'),
            (106, 'JM', 'JAMAICA', 'Jamaica', 'JAM', '388', 1876, 'Jamaican', 'Enable'),
            (107, 'JP', 'JAPAN', 'Japan', 'JPN', '392', 81, 'Japanese', 'Enable'),
            (108, 'JO', 'JORDAN', 'Jordan', 'JOR', '400', 962, 'Jordanian', 'Enable'),
            (109, 'KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', '398', 7, 'Kazakhstani, Kazakh', 'Enable'),
            (110, 'KE', 'KENYA', 'Kenya', 'KEN', '404', 254, 'Kenyan', 'Enable'),
            (111, 'KI', 'KIRIBATI', 'Kiribati', 'KIR', '296', 686, 'I-Kiribati', 'Enable'),
            (112, 'KP', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'Korea, Democratic People\'s Republic of', 'PRK', '408', 850, 'Zimbabwean', 'Enable'),
            (113, 'KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', '410', 82, 'Zimbabwean', 'Enable'),
            (114, 'KW', 'KUWAIT', 'Kuwait', 'KWT', '414', 965, 'Kuwaiti', 'Enable'),
            (115, 'KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', '417', 996, 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz', 'Enable'),
            (116, 'LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'Lao People\'s Democratic Republic', 'LAO', '418', 856, 'Zimbabwean', 'Enable'),
            (117, 'LV', 'LATVIA', 'Latvia', 'LVA', '428', 371, 'Latvian', 'Enable'),
            (118, 'LB', 'LEBANON', 'Lebanon', 'LBN', '422', 961, 'Lebanese', 'Enable'),
            (119, 'LS', 'LESOTHO', 'Lesotho', 'LSO', '426', 266, 'Basotho', 'Enable'),
            (120, 'LR', 'LIBERIA', 'Liberia', 'LBR', '430', 231, 'Liberian', 'Enable'),
            (121, 'LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', '434', 218, 'Zimbabwean', 'Enable'),
            (122, 'LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', '438', 423, 'Liechtenstein', 'Enable'),
            (123, 'LT', 'LITHUANIA', 'Lithuania', 'LTU', '440', 370, 'Lithuanian', 'Enable'),
            (124, 'LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', '442', 352, 'Luxembourg, Luxembourgish', 'Enable'),
            (125, 'MO', 'MACAO', 'Macao', 'MAC', '446', 853, 'Macanese, Chinese', 'Enable'),
            (126, 'MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', '807', 389, 'Zimbabwean', 'Enable'),
            (127, 'MG', 'MADAGASCAR', 'Madagascar', 'MDG', '450', 261, 'Malagasy', 'Enable'),
            (128, 'MW', 'MALAWI', 'Malawi', 'MWI', '454', 265, 'Malawian', 'Enable'),
            (129, 'MY', 'MALAYSIA', 'Malaysia', 'MYS', '458', 60, 'Malaysian', 'Enable'),
            (130, 'MV', 'MALDIVES', 'Maldives', 'MDV', '462', 960, 'Maldivian', 'Enable'),
            (131, 'ML', 'MALI', 'Mali', 'MLI', '466', 223, 'Malian, Malinese', 'Enable'),
            (132, 'MT', 'MALTA', 'Malta', 'MLT', '470', 356, 'Maltese', 'Enable'),
            (133, 'MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', '584', 692, 'Marshallese', 'Enable'),
            (134, 'MQ', 'MARTINIQUE', 'Martinique', 'MTQ', '474', 596, 'Martiniquais, Martinican', 'Enable'),
            (135, 'MR', 'MAURITANIA', 'Mauritania', 'MRT', '478', 222, 'Mauritanian', 'Enable'),
            (136, 'MU', 'MAURITIUS', 'Mauritius', 'MUS', '480', 230, 'Mauritian', 'Enable'),
            (137, 'YT', 'MAYOTTE', 'Mayotte', '', '', 269, 'Mahoran', 'Enable'),
            (138, 'MX', 'MEXICO', 'Mexico', 'MEX', '484', 52, 'Mexican', 'Enable'),
            (139, 'FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', '583', 691, 'Zimbabwean', 'Enable'),
            (140, 'MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', '498', 373, 'Zimbabwean', 'Enable'),
            (141, 'MC', 'MONACO', 'Monaco', 'MCO', '492', 377, 'Monégasque, Monacan', 'Enable'),
            (142, 'MN', 'MONGOLIA', 'Mongolia', 'MNG', '496', 976, 'Mongolian', 'Enable'),
            (143, 'MS', 'MONTSERRAT', 'Montserrat', 'MSR', '500', 1664, 'Montserratian', 'Enable'),
            (144, 'MA', 'MOROCCO', 'Morocco', 'MAR', '504', 212, 'Moroccan', 'Enable'),
            (145, 'MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', '508', 258, 'Mozambican', 'Enable'),
            (146, 'MM', 'MYANMAR', 'Myanmar', 'MMR', '104', 95, 'Burmese', 'Enable'),
            (147, 'NA', 'NAMIBIA', 'Namibia', 'NAM', '516', 264, 'Namibian', 'Enable'),
            (148, 'NR', 'NAURU', 'Nauru', 'NRU', '520', 674, 'Nauruan', 'Enable'),
            (149, 'NP', 'NEPAL', 'Nepal', 'NPL', '524', 977, 'Nepali, Nepalese', 'Enable'),
            (150, 'NL', 'NETHERLANDS', 'Netherlands', 'NLD', '528', 31, 'Dutch, Netherlandic', 'Enable'),
            (151, 'AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', '530', 599, 'Zimbabwean', 'Enable'),
            (152, 'NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', '540', 687, 'New Caledonian', 'Enable'),
            (153, 'NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', '554', 64, 'New Zealand, NZ', 'Enable'),
            (154, 'NI', 'NICARAGUA', 'Nicaragua', 'NIC', '558', 505, 'Nicaraguan', 'Enable'),
            (155, 'NE', 'NIGER', 'Niger', 'NER', '562', 227, 'Nigerien', 'Enable'),
            (156, 'NG', 'NIGERIA', 'Nigeria', 'NGA', '566', 234, 'Nigerian', 'Enable'),
            (157, 'NU', 'NIUE', 'Niue', 'NIU', '570', 683, 'Niuean', 'Enable'),
            (158, 'NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', '574', 672, 'Norfolk Island', 'Enable'),
            (159, 'MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', '580', 1670, 'Northern Marianan', 'Enable'),
            (160, 'NO', 'NORWAY', 'Norway', 'NOR', '578', 47, 'Norwegian', 'Enable'),
            (161, 'OM', 'OMAN', 'Oman', 'OMN', '512', 968, 'Omani', 'Enable'),
            (162, 'PK', 'PAKISTAN', 'Pakistan', 'PAK', '586', 92, 'Pakistani', 'Enable'),
            (163, 'PW', 'PALAU', 'Palau', 'PLW', '585', 680, 'Palauan', 'Enable'),
            (164, 'PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', '', '', 970, 'Zimbabwean', 'Enable'),
            (165, 'PA', 'PANAMA', 'Panama', 'PAN', '591', 507, 'Panamanian', 'Enable'),
            (166, 'PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', '598', 675, 'Papua New Guinean, Papuan', 'Enable'),
            (167, 'PY', 'PARAGUAY', 'Paraguay', 'PRY', '600', 595, 'Paraguayan', 'Enable'),
            (168, 'PE', 'PERU', 'Peru', 'PER', '604', 51, 'Peruvian', 'Enable'),
            (169, 'PH', 'PHILIPPINES', 'Philippines', 'PHL', '608', 63, 'Philippine, Filipino', 'Enable'),
            (170, 'PN', 'PITCAIRN', 'Pitcairn', 'PCN', '612', 0, 'Pitcairn Island', 'Enable'),
            (171, 'PL', 'POLAND', 'Poland', 'POL', '616', 48, 'Polish', 'Enable'),
            (172, 'PT', 'PORTUGAL', 'Portugal', 'PRT', '620', 351, 'Portuguese', 'Enable'),
            (173, 'PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', '630', 1787, 'Puerto Rican', 'Enable'),
            (174, 'QA', 'QATAR', 'Qatar', 'QAT', '634', 974, 'Qatari', 'Enable'),
            (175, 'RE', 'REUNION', 'Reunion', 'REU', '638', 262, 'Réunionese, Réunionnais', 'Enable'),
            (176, 'RO', 'ROMANIA', 'Romania', 'ROM', '642', 40, 'Romanian', 'Enable'),
            (177, 'RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', '643', 70, 'Russian', 'Enable'),
            (178, 'RW', 'RWANDA', 'Rwanda', 'RWA', '646', 250, 'Rwandan', 'Enable'),
            (179, 'SH', 'SAINT HELENA', 'Saint Helena', 'SHN', '654', 290, 'Zimbabwean', 'Enable'),
            (180, 'KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', '659', 1869, 'Kittitian or Nevisian', 'Enable'),
            (181, 'LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', '662', 1758, 'Saint Lucian', 'Enable'),
            (182, 'PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', '666', 508, 'Saint-Pierrais or Miquelonnais', 'Enable'),
            (183, 'VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', '670', 1784, 'Saint Vincentian, Vincentian', 'Enable'),
            (184, 'WS', 'SAMOA', 'Samoa', 'WSM', '882', 684, 'Samoan', 'Enable'),
            (185, 'SM', 'SAN MARINO', 'San Marino', 'SMR', '674', 378, 'Sammarinese', 'Enable'),
            (186, 'ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', '678', 239, 'São Toméan', 'Enable'),
            (187, 'SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', '682', 966, 'Saudi, Saudi Arabian', 'Enable'),
            (188, 'SN', 'SENEGAL', 'Senegal', 'SEN', '686', 221, 'Senegalese', 'Enable'),
            (189, 'CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', '', '', 381, 'Zimbabwean', 'Enable'),
            (190, 'SC', 'SEYCHELLES', 'Seychelles', 'SYC', '690', 248, 'Seychellois', 'Enable'),
            (191, 'SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', '694', 232, 'Sierra Leonean', 'Enable'),
            (192, 'SG', 'SINGAPORE', 'Singapore', 'SGP', '702', 65, 'Singaporean', 'Enable'),
            (193, 'SK', 'SLOVAKIA', 'Slovakia', 'SVK', '703', 421, 'Slovak', 'Enable'),
            (194, 'SI', 'SLOVENIA', 'Slovenia', 'SVN', '705', 386, 'Slovenian, Slovene', 'Enable'),
            (195, 'SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', '90', 677, 'Solomon Island', 'Enable'),
            (196, 'SO', 'SOMALIA', 'Somalia', 'SOM', '706', 252, 'Somali, Somalian', 'Enable'),
            (197, 'ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', '710', 27, 'South African', 'Enable'),
            (198, 'GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', '', '', 0, 'South Georgia or South Sandwich Islands', 'Enable'),
            (199, 'ES', 'SPAIN', 'Spain', 'ESP', '724', 34, 'Spanish', 'Enable'),
            (200, 'LK', 'SRI LANKA', 'Sri Lanka', 'LKA', '144', 94, 'Sri Lankan', 'Enable'),
            (201, 'SD', 'SUDAN', 'Sudan', 'SDN', '736', 249, 'Sudanese', 'Enable'),
            (202, 'SR', 'SURINAME', 'Suriname', 'SUR', '740', 597, 'Surinamese', 'Enable'),
            (203, 'SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', '744', 47, 'Svalbard', 'Enable'),
            (204, 'SZ', 'SWAZILAND', 'Swaziland', 'SWZ', '748', 268, 'Swazi', 'Enable'),
            (205, 'SE', 'SWEDEN', 'Sweden', 'SWE', '752', 46, 'Swedish', 'Enable'),
            (206, 'CH', 'SWITZERLAND', 'Switzerland', 'CHE', '756', 41, 'Swiss', 'Enable'),
            (207, 'SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', '760', 963, 'Syrian', 'Enable'),
            (208, 'TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', '158', 886, 'Chinese, Taiwanese', 'Enable'),
            (209, 'TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', '762', 992, 'Tajikistani', 'Enable'),
            (210, 'TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', '834', 255, 'Tanzanian', 'Enable'),
            (211, 'TH', 'THAILAND', 'Thailand', 'THA', '764', 66, 'Thai', 'Enable'),
            (212, 'TL', 'TIMOR-LESTE', 'Timor-Leste', '', '', 670, 'Timorese', 'Enable'),
            (213, 'TG', 'TOGO', 'Togo', 'TGO', '768', 228, 'Togolese', 'Enable'),
            (214, 'TK', 'TOKELAU', 'Tokelau', 'TKL', '772', 690, 'Tokelauan', 'Enable'),
            (215, 'TO', 'TONGA', 'Tonga', 'TON', '776', 676, 'Tongan', 'Enable'),
            (216, 'TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', '780', 1868, 'Trinidadian or Tobagonian', 'Enable'),
            (217, 'TN', 'TUNISIA', 'Tunisia', 'TUN', '788', 216, 'Tunisian', 'Enable'),
            (218, 'TR', 'TURKEY', 'Turkey', 'TUR', '792', 90, 'Turkish', 'Enable'),
            (219, 'TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', '795', 7370, 'Turkmen', 'Enable'),
            (220, 'TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', '796', 1649, 'Turks and Caicos Island', 'Enable'),
            (221, 'TV', 'TUVALU', 'Tuvalu', 'TUV', '798', 688, 'Tuvaluan', 'Enable'),
            (222, 'UG', 'UGANDA', 'Uganda', 'UGA', '800', 256, 'Ugandan', 'Enable'),
            (223, 'UA', 'UKRAINE', 'Ukraine', 'UKR', '804', 380, 'Ukrainian', 'Enable'),
            (224, 'AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', '784', 971, 'Emirati, Emirian, Emiri', 'Enable'),
            (225, 'GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', '826', 44, 'Zimbabwean', 'Enable'),
            (226, 'US', 'UNITED STATES', 'United States', 'USA', '840', 1, 'Zimbabwean', 'Enable'),
            (227, 'UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', '', '', 1, 'American', 'Enable'),
            (228, 'UY', 'URUGUAY', 'Uruguay', 'URY', '858', 598, 'Uruguayan', 'Enable'),
            (229, 'UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', '860', 998, 'Uzbekistani, Uzbek', 'Enable'),
            (230, 'VU', 'VANUATU', 'Vanuatu', 'VUT', '548', 678, 'Ni-Vanuatu, Vanuatuan', 'Enable'),
            (231, 'VE', 'VENEZUELA', 'Venezuela', 'VEN', '862', 58, 'Zimbabwean', 'Enable'),
            (232, 'VN', 'VIET NAM', 'Viet Nam', 'VNM', '704', 84, 'Zimbabwean', 'Enable'),
            (233, 'VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', '92', 1284, 'Zimbabwean', 'Enable'),
            (234, 'VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', '850', 1340, 'Zimbabwean', 'Enable'),
            (235, 'WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', '876', 681, 'Wallis and Futuna, Wallisian or Futunan', 'Enable'),
            (236, 'EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', '732', 212, 'Sahrawi, Sahrawian, Sahraouian', 'Enable'),
            (237, 'YE', 'YEMEN', 'Yemen', 'YEM', '887', 967, 'Yemeni', 'Enable'),
            (238, 'ZM', 'ZAMBIA', 'Zambia', 'ZMB', '894', 260, 'Zambian', 'Enable'),
            (239, 'ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', '716', 263, 'Zimbabwean', 'Enable')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
